engines:
  duplications:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - server/**
    - server/**/**
    - client/**
    - client/**/**
languages:
  JavaScript: true
exclude_paths:
  - server/models/index.js
  - test/