sudo: required
dist: trusty
language: node_js
node_js:
  - 6
services:
  - postgresql
before_script:
  - npm install -g sequelize-cli
  - sudo -u postgres createuser bunmialao
  - createdb postit-test
  - sequelize db:migrate
script:
  - npm run test