export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const ADD_MEMBER_TO_GROUP = 'ADD_MEMBER_TO_GROUP';
export const LOAD_GROUPS = 'LOAD_GROUPS';

